#!/usr/bin/env python3
"""
clean_marker_output.py — Post-processes Markdown files generated by Marker
(PDF-to-Markdown converter) to optimize them for RAG indexing.

Usage:
    python clean_marker_output.py <input_file.md>

Output is written to docs/<filename>, overwriting if already there.
"""

import re
import sys
import argparse
from collections import Counter
from datetime import date
from pathlib import Path

DOCS_DIR = Path("docs")

# ─── Footer patterns ──────────────────────────────────────────────────────────

_FOOTER_PATTERNS = [
    re.compile(r"^\+?[\d\s\(\)\-\.]{9,}$"),                          # phone numbers
    re.compile(r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}"),# email
    re.compile(r"(©|Copyright\s+\d{4})", re.IGNORECASE),             # copyright
    re.compile(r"^https?://\S+$"),                                    # bare URL
    re.compile(r"^www\.\S+\.\S+$"),                                   # bare www URL
    re.compile(r"(subject to (regulatory )?export control"
               r"|all rights reserved"
               r"|printed in)",
               re.IGNORECASE),
]


# ─── Category inference ───────────────────────────────────────────────────────

_CATEGORY_KEYWORDS = [
    (["radio", "mesh", "cofdm", "rf ", "antenna", "frequency", "netnode"],
     "comunicações"),
    (["sonar", "acoustic", "sidescan", "edgetech"],
     "sensores acústicos"),
    (["engine", "fuel", "outboard", "powerhead", "ignition", "gear housing",
      "mercury", "optimax"],
     "propulsão"),
    (["navigation", "gps", "ins", "dvl"],
     "navegação"),
    (["camera", "video", "payload", "sdi"],
     "payload / sensores ópticos"),
]


def _infer_frontmatter(file_path: Path, content: str) -> dict:
    content_lower = content.lower()

    # Title: first H1 or H2 heading, stripped of markdown bold markers
    titulo = file_path.stem.replace("-", " ").replace("_", " ")
    m = re.search(r"^#{1,2}\s+\*{0,2}(.+?)\*{0,2}\s*$", content, re.MULTILINE)
    if m:
        titulo = m.group(1).strip()

    categoria = "documentação técnica"
    for keywords, cat in _CATEGORY_KEYWORDS:
        if any(kw in content_lower for kw in keywords):
            categoria = cat
            break

    return {
        "titulo": titulo,
        "categoria": categoria,
        "data_indexacao": date.today().isoformat(),
        "classificacao": "interno",
    }


def _build_frontmatter(meta: dict) -> str:
    lines = ["---"]
    for key, value in meta.items():
        safe = str(value)
        if any(c in safe for c in ':#{}[]|>&'):
            lines.append(f'{key}: "{safe}"')
        else:
            lines.append(f"{key}: {safe}")
    lines.append("---")
    return "\n".join(lines)


# ─── Cleaners ─────────────────────────────────────────────────────────────────

def _strip_existing_frontmatter(content: str) -> str:
    if content.startswith("---"):
        end = content.find("\n---\n", 3)
        if end != -1:
            return content[end + 5:]
    return content


def _remove_image_refs(content: str) -> str:
    """Remove ![](_page_X_Picture_Y.jpeg) and similar Marker image stubs."""
    return re.sub(r"!\[[^\]]*\]\([^)]*\)", "", content)


def _remove_repeated_headings(content: str) -> str:
    """Keep only the first occurrence of any heading that repeats (PDF page headers)."""
    lines = content.split("\n")

    heading_counts = Counter(
        line.strip() for line in lines if line.strip().startswith("#")
    )
    repeated = {h for h, n in heading_counts.items() if n > 1}

    seen: set[str] = set()
    out = []
    for line in lines:
        stripped = line.strip()
        if stripped in repeated:
            if stripped in seen:
                continue
            seen.add(stripped)
        out.append(line)
    return "\n".join(out)


def _remove_page_continuation_headings(content: str) -> str:
    """Remove headings like '### **Technical Specification (cont.):**' added by
    Marker to carry the section title onto the next PDF page."""
    # Allow optional bold markers (**) around the title text and after the colon
    return re.sub(
        r"^#{1,4}\s+\**\s*.+?\s*\(cont\.?\)\s*:?\**\s*$",
        "",
        content,
        flags=re.IGNORECASE | re.MULTILINE,
    )


def _remove_footers(content: str) -> str:
    """Remove lines that match known footer patterns."""
    lines = content.split("\n")
    out = []
    for line in lines:
        stripped = line.strip()
        # Strip markdown bold/italic before matching
        plain = re.sub(r"\*{1,2}|_{1,2}", "", stripped)
        if any(p.search(plain) for p in _FOOTER_PATTERNS):
            continue
        out.append(line)
    return "\n".join(out)


def _remove_empty_table_rows(content: str) -> str:
    """Remove table rows where every cell is blank (Marker inserts them as padding)."""
    lines = content.split("\n")
    out = []
    for line in lines:
        if re.match(r"^\s*\|(\s*\|)+\s*$", line):
            continue
        out.append(line)
    return "\n".join(out)


def _fix_single_column_tables(content: str) -> str:
    """Convert tables whose every data row has exactly one cell into bullet lists.

    Single-column tables are a Marker artefact: the PDF had a multi-column
    table but only one column survived the conversion.  A plain list is more
    useful for RAG retrieval than a broken one-column table.
    """
    out_lines: list[str] = []
    lines = content.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if "|" not in line:
            out_lines.append(line)
            i += 1
            continue

        # Collect the full table block
        table_block: list[str] = []
        j = i
        while j < len(lines) and "|" in lines[j]:
            table_block.append(lines[j])
            j += 1

        # Decide: single-column or not?
        data_rows = [
            r for r in table_block
            if not re.match(r"^\s*\|[\s\-|]+\|\s*$", r)  # skip separator rows
        ]
        is_single = all(
            len([c for c in r.strip().strip("|").split("|") if c.strip()]) == 1
            for r in data_rows
        ) and len(data_rows) >= 1

        if is_single:
            for r in data_rows:
                cell = r.strip().strip("|").strip()
                if cell:
                    out_lines.append(f"- {cell}")
        else:
            out_lines.extend(table_block)

        i = j
    return "\n".join(out_lines)


def _collapse_blank_lines(content: str) -> str:
    """Enforce a maximum of 2 consecutive blank lines."""
    # \n\n\n = 2 blank lines; \n{4,} = 3+ blank lines
    return re.sub(r"\n{4,}", "\n\n\n", content)


# ─── Pipeline ─────────────────────────────────────────────────────────────────

def clean(input_path: Path) -> Path:
    content = input_path.read_text(encoding="utf-8")

    content = _strip_existing_frontmatter(content)
    content = _remove_image_refs(content)
    content = _remove_footers(content)
    content = _remove_page_continuation_headings(content)
    content = _remove_repeated_headings(content)
    content = _remove_empty_table_rows(content)
    content = _fix_single_column_tables(content)
    content = _collapse_blank_lines(content)
    content = content.strip()

    meta = _infer_frontmatter(input_path, content)
    frontmatter = _build_frontmatter(meta)
    content = frontmatter + "\n\n" + content + "\n"

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = DOCS_DIR / input_path.name
    output_path.write_text(content, encoding="utf-8")
    return output_path


# ─── Report helpers ───────────────────────────────────────────────────────────

def _diff_stats(original: str, cleaned: str) -> None:
    orig_lines  = original.count("\n")
    clean_lines = cleaned.count("\n")
    delta       = clean_lines - orig_lines          # negative = lines removed
    print(f"   Lines:   {orig_lines} → {clean_lines}  ({delta:+d})")

    orig_tables  = original.count("|---|")
    clean_tables = cleaned.count("|---|")
    if orig_tables != clean_tables:
        print(f"   Tables:  {orig_tables} → {clean_tables}")


# ─── Entry point ──────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Post-process Marker-generated Markdown for RAG indexing."
    )
    parser.add_argument("input", help="Path to the .md file to clean")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"error: file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    original = input_path.read_text(encoding="utf-8")

    print(f"Input:  {input_path}")
    output_path = clean(input_path)
    cleaned = output_path.read_text(encoding="utf-8")
    print(f"Output: {output_path}")
    _diff_stats(original, cleaned)


if __name__ == "__main__":
    main()
